import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "chatGPT Clone",
  description: "Generated by sxvljxh",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html>
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (

            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <Sidebar />
              </div>
              {/* <ClientProvider /> - Toast Notifications */}
              <ClientProvider />
              <div className="flex-1 bg-[#343541]">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
